chat/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views

urlpatterns = [
    path('', views.home, name='home'),
    # path('admin/', admin.site.urls),

    path('common/', views.common, name='common'),

    path('contacts/', views.contacts),
    path('messages/<int:recipient_id>/', views.messages),
    path('messages/add/', views.add),
    
    path('users/', include('users.urls', namespace="users")),
]

# try:
#     from .local_settings import *
# except ImportError:
#     from .prod_settings import *

users/urls.py
app_name = "users"

from django.urls import path
from . import views

urlpatterns = [
    path('registration/', views.register_user, name='registration'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile_form_handler, name='profile'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Message(models.Model):
    sender = models.ForeignKey(User, related_name='senders', default=0, on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='recipients', default=0, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField()

users/models.py
from django.db import models

# Create your models here.

users/forms/login_form.py
from django import forms
from django.contrib.auth import get_user_model


class LoginUserForm(forms.Form):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

users/forms/profile_form.py
from django import forms
from django.contrib.auth import get_user_model


class ProfileForm(forms.Form):
    hide_button = False
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input', 'disabled': None}))
    # email = forms.EmailField(label='Почта', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    # password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    # password_new = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    # password_new_again = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password']

users/forms/register_form.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

class RegistrationUserForm(forms.ModelForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

    def clean_password2(self):
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']

        if password != password2:
            raise ValidationError("пароли не совпадают")

main/views.py
from django.shortcuts import render
from .models import Message
from django.http import JsonResponse, Http404
from django.utils import timezone
import json
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from users.forms.login_form import LoginUserForm

def home(request):
    context = {}

    if not request.user.is_authenticated:
        form_data = request.POST if request.method == 'POST' else None
        context['login_form'] = LoginUserForm(form_data)

    return render(request, 'home.html', context)


@login_required
def contacts(request):
    users = User.objects.exclude(id=request.user.id)

    return JsonResponse({
       'contacts': list(map(lambda user: {
            'id': user.id,
            'name': user.username,
        }, users))
    })


@login_required
def messages(request, recipient_id):
    if not recipient_id:
        return JsonResponse({
            'errors': [
                'wrong recipient'
            ]
        })

    my_id = request.user.id

    messages = Message.objects.filter(
        (Q(sender=my_id) & Q(recipient=recipient_id))
        | (Q(sender=recipient_id) & Q(recipient=my_id))
    )

    return JsonResponse({
       'messages': list(map(lambda m: {
            'sender_id': m.sender.id,
            'recipient_id': m.recipient.id,
            'date': m.date,
            'text': m.text,
        }, messages))
    })


@login_required
def add(request):
    sender_id = request.user.id
    request_data = json.loads(request.body)
    recipient_id = int(request_data['recipient_id'] or 0)

    if not recipient_id or request_data['text'] == '':
        return JsonResponse({
            'status': False,
        })

    message = Message(
        sender_id = sender_id,
        recipient_id = recipient_id,
        text = request_data['text'],
        date = timezone.now()
    )

    message.save()

    messages = Message.objects.filter(
        (Q(sender=sender_id) & Q(recipient=recipient_id))
        | (Q(sender=recipient_id) & Q(recipient=sender_id))
    )

    return JsonResponse({
        'status': True,
        'messages': list(map(lambda m: {
            'sender_id': m.sender.id,
            'recipient_id': m.recipient.id,
            'date': m.date,
            'text': m.text,
        }, messages)),
    })


@login_required
def common(request):
    user = User.objects.get(id=request.user.id)

    if user is None:
        return Http404()

    return JsonResponse({
       'user': {
            'id': user.id,
            'name': user.username,
        }
    })

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseForbidden, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from users.forms.login_form import LoginUserForm
from users.forms.register_form import RegistrationUserForm
from users.forms.profile_form import ProfileForm


def register_user(request):
    if request.method not in ('GET', 'POST'):
        return Http404()

    if request.method == 'GET':
        form = RegistrationUserForm()
    
    if request.method == 'POST':
        form = RegistrationUserForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()

            return login_user(request)
        
    return render(request, 'registration.html', {'form': form})


def login_user(request):
    if request.method not in ('GET', 'POST'):
        return Http404()

    if request.method == 'GET':
        form = LoginUserForm()
    
    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        
        if form.is_valid():
            user_data = form.cleaned_data
            user = authenticate(request, username=user_data['username'], password=user_data['password'])

            if user and user.is_active:
                login(request, user)

                return HttpResponseRedirect(reverse('home'))
            
            form.add_error('username', 'Неправильный логин или пароль')

    return render(request, 'login.html', {'form': form})


@login_required
def logout_user(request):
    logout(request)

    return HttpResponseRedirect(reverse('home'))


def profile_form_handler(request):
    if request.method not in ('GET', 'POST'):
        return Http404()

    user = User.objects.get(id=request.user.id)

    if not user or not user.is_active:
        return HttpResponseForbidden()

    if request.method == 'GET':
        form = ProfileForm()
        form.fields["username"].initial = user.username
    
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        
        if form.is_valid():
            user_data = form.cleaned_data
            user.email = user_data['email']
            user.save()

    return render(request, 'profile.html', {'form': form})

main/templates/footer.html
<footer>
</footer>

main/templates/header.html
<header>
    <div id="logo" class="panel">C h a T</div>
</header>

main/templates/home.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>chat</title>
        {% load static %}
        <link rel="icon" href="{% static 'favicon.ico' %}" />
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        {% csrf_token %}
        {% if user.is_authenticated %}
            <div id="app"></div>
            <script src="{% static 'js/index.js' %}"></script>
        {% else %}
            {% include "header.html" %}
            <main>
                <div class="form-panel-wrapper">
                    {% url 'users:login' as login_form_url %}
                    {% include "one_form.html" with form=login_form action=login_form_url submit_button_text="Войти" csrf_token=csrf_token only %}
                    <a id="registration_link" href="{% url 'users:registration' %}">регистрация</a>
                </div>
            </main>
            {% include "footer.html" %}
            {% endif %}
    </body>
</html>

main/templates/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>chat</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    {% include "header.html" %}
    <main>
        <div class="form-panel-wrapper">
            {% url 'users:login' as login_form_url %}
            {% include "one_form.html" with form=form action=login_form_url submit_button_text="Войти" %}
        </div>
    </main>
    {% include "footer.html" %}
</body>
</html>

main/templates/one_form.html
    <div class="panel one-form-panel">
        <form name="user" {% if action %}action="{{ action }}"{% endif %} method="post" class="one-form">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            <table>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}:</label></th>
                    <td>{{ field }}</td>
                </tr>
                {% if field.errors %}
                    <tr>
                        <th></th>
                        <td><div class="form-error">{{ field.errors }}</div></td>
                    </tr>
                {% endif %}
            {% endfor %}
            </table>
            {% if submit_button_text %}
            <div class="one-form-buttons">
                <button type="submit">{{ submit_button_text }}</button>
            </div>
            {% endif %}
        </form>
    </div>

main/templates/profile.html
<div class="form-panel-wrapper">
    {% url 'users:profile' as profile_form_url %}
    {% include "one_form.html" with form=form action=profile_form_url csrf_token=csrf_token only %}
</div>

main/templates/registration.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>chat</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    {% include "header.html" %}
    <main>
        <div class="form-panel-wrapper">
            {% url 'users:registration' as registration_form_url %}
            {% include "one_form.html" with form=form action=registration_form_url submit_button_text="Регистрация" csrf_token=csrf_token only %}
        </div>
    </main>
    {% include "footer.html" %}
</body>
</html>